<a href="https://colab.research.google.com/github/iris-obed/AI-Data-Engineer-Assignments/blob/master/Implementing_matrix_multiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Problem 1:** Calculating matrix multiplication by hand


**Given Matrices**:

**Matrix ( A )**:
[
A =
\begin{bmatrix}
-1 & 2 & 3 \
4 & -5 & 6 \
7 & 8 & -9 \
\end{bmatrix}
]

**Matrix ( B )**:
[
B =
\begin{bmatrix}
0 & 2 & 1 \
0 & 2 & -8 \
2 & 9 & -1 \
\end{bmatrix}
]


**Matrix Multiplication Process**:

1- Dot Product Calculation: For each element ( c_{ij} ) in the resulting matrix ( C ), you sum the products of the corresponding elements from the ( i )-th row of matrix ( A ) and the ( j )-th column of matrix ( B ).



2- Matrix Dimensions: Matrix ( A ) is ( 3 \times 3 ) and matrix ( B ) is ( 3 \times 3 ). The resulting matrix ( C ) will also be ( 3 \times 3 ).


Calculation of Elements in Matrix ( C ):

Element ( c_{11} ):
[
c_{11} = (-1)(0) + (2)(0) + (3)(2) = 0 + 0 + 6 = 6
]

Element ( c_{12} ):
[
c_{12} = (-1)(2) + (2)(2) + (3)(9) = -2 + 4 + 27 = 29
]

Element ( c_{13} ):
[
c_{13} = (-1)(1) + (2)(-8) + (3)(-1) = -1 - 16 - 3 = -20
]

Element ( c_{21} ):
[
c_{21} = (4)(0) + (-5)(0) + (6)(2) = 0 + 0 + 12 = 12
]

Element ( c_{22} ):
[
c_{22} = (4)(2) + (-5)(2) + (6)(9) = 8 - 10 + 54 = 52
]

Element ( c_{23} ):
[
c_{23} = (4)(1) + (-5)(-8) + (6)(-1) = 4 + 40 - 6 = 38
]

Element ( c_{31} ):
[
c_{31} = (7)(0) + (8)(0) + (-9)(2) = 0 + 0 - 18 = -18
]

Element ( c_{32} ):
[
c_{32} = (7)(2) + (8)(2) + (-9)(9) = 14 + 16 - 81 = -51
]

Element ( c_{33} ):
[
c_{33} = (7)(1) + (8)(-8) + (-9)(-1) = 7 - 64 + 9 = -48
]

**Resulting Matrix ( C )**:

[
C =
\begin{bmatrix}
6 & 29 & -20 \
12 & 52 & 38 \
-18 & -51 & -48 \
\end{bmatrix}
]

# **Problem 2**: Calculation using NumPy functions

In [2]:
import numpy as np

# Given Matrices
A = np.array([[-1, 2, 3],
              [4, -5, 6],
              [7, 8, -9]])

B = np.array([[0, 2, 1],
              [0, 2, -8],
              [2, 9, -1]])

# Calculating the matrix product using np.matmul()
C_matmul = np.matmul(A, B)

# Calculating the matrix product using np.dot()
C_dot = np.dot(A, B)

# Calculating the matrix product using @
C_at = A @ B

# Resulting Matrices
print("Result using np.matmul():\n", C_matmul)
print("\nResult using np.dot():\n", C_dot)
print("\nResult using operador @:\n", C_at)

Result using np.matmul():
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]

Result using np.dot():
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]

Result using operador @:
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


# **Problem 3**: Implementing calculations for a certain element

In [5]:
import numpy as np

# Given Matrices
A = np.array([[-1, 2, 3],
              [4, -5, 6],
              [7, 8, -9]])

B = np.array([[0, 2, 1],
              [0, 2, -8],
              [2, 9, -1]])

# Initializing the C matrix with zeros
rows_A, cols_A = A.shape
rows_B, cols_B = B.shape
C = np.zeros((rows_A, cols_B))

# Implementing the matrix product without np.matmul() or np.dot()
for i in range(rows_A):
    for j in range(cols_B):
        for k in range(cols_A):
            C[i][j] += A[i][k] * B[k][j]

# Resulting Matrix
print("Matrix C (result of A * B):")
print(C)

Matrix C (result of A * B):
[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


# **Problem 4**: Creating a function to perform matrix multiplication

In [7]:
import numpy as np

def matrix_multiply(A, B):
    # Obtains the dimensions of the matrices
    rows_A, cols_A = len(A), len(A[0])
    rows_B, cols_B = len(B), len(B[0])

    # Initializes the result matrix C with zeros
    C = [[0] * cols_B for _ in range(rows_A)]

    # Matrix multiplication
    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):
                C[i][j] += A[i][k] * B[k][j]

    return C

# Given Matrices
A = [[-1, 2, 3],
     [4, -5, 6],
     [7, 8, -9]]

B = [[0, 2, 1],
     [0, 2, -8],
     [2, 9, -1]]

# Calculate the product of matrices
C = matrix_multiply(A, B)

# Result
print("Matrix C (result of A * B):")
for row in C:
    print(row)

Matrix C (result of A * B):
[6, 29, -20]
[12, 52, 38]
[-18, -51, -48]


# **Problem 5**: Evaluating inputs that are not defined

In [12]:
def validate_and_multiply(D, E):
    # Check the dimensions of the matrices
    rows_D, cols_D = len(D), len(D[0])
    rows_E, cols_E = len(E), len(E[0])

    # Verifica se a multiplicação é possível
    if cols_D != rows_E:
        return ("Error: Matrix multiplication not defined."
         "Number of columns in the first matrix must equal the number of rows in the second matrix.")

    # Initializes the result matrix C with zeros
    F = [[0] * cols_E for _ in range(rows_D)]

    # Matrix multiplication
    for i in range(rows_D):
        for j in range(cols_E):
            for k in range(cols_D):
                F[i][j] += D[i][k] * E[k][j]

    return F

# Given Matrices
D = [[-1, 2, 3],
     [4, -5, 6]]

E = [[-9, 8, 7],
     [6, -5, 4]]

# Testing multiplication
result = validate_and_multiply(D, E)

# Shows the result or error
print(result)




Error: Matrix multiplication not defined.Number of columns in the first matrix must equal the number of rows in the second matrix.


# **Problem 6**: Transposition

In [14]:
import numpy as np

# Given Matrices
D = np.array([[-1, 2, 3],
              [4, -5, 6]])

E = np.array([[-9, 8, 7],
              [6, -5, 4]])

# Transpose matrix E
E_T = np.transpose(E)

# Check that multiplications now possible
#Number of columns in D must be equal to the number of rows in E_T
if D.shape[1] == E_T.shape[0]:
    C = np.matmul(D, E_T)  #
    print("Result of multiplication after transposition:")
    print(C)
else:
    print("Error: Multiplication is not yet defined after transposition.")

Result of multiplication after transposition:
[[ 46  -4]
 [-34  73]]
